# This file was automatically generated by SWIG (http://www.swig.org).
# Version 1.3.40
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.
# This file is compatible with both classic and new-style classes.

from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_vrpn_Analog', [dirname(__file__)])
        except ImportError:
            import _vrpn_Analog
            return _vrpn_Analog
        if fp is not None:
            try:
                _mod = imp.load_module('_vrpn_Analog', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _vrpn_Analog = swig_import_helper()
    del swig_import_helper
else:
    import _vrpn_Analog
del version_info
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static) or hasattr(self,name):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

vrpn_DEFAULT_LISTEN_PORT_NO = _vrpn_Analog.vrpn_DEFAULT_LISTEN_PORT_NO
VRPN_SYSTEMDRIVE = _vrpn_Analog.VRPN_SYSTEMDRIVE
VRPN_PHASESPACE_LIB_PATH = _vrpn_Analog.VRPN_PHASESPACE_LIB_PATH
VRPN_WIIUSE_H = _vrpn_Analog.VRPN_WIIUSE_H
VRPN_WIIUSE_LIB_PATH = _vrpn_Analog.VRPN_WIIUSE_LIB_PATH
VRPN_FREESPACE_LIB_PATH = _vrpn_Analog.VRPN_FREESPACE_LIB_PATH
VRPN_TRIVISIOCOLIBRI_H = _vrpn_Analog.VRPN_TRIVISIOCOLIBRI_H
VRPN_TRIVISIOCOLIBRI_LIB_PATH = _vrpn_Analog.VRPN_TRIVISIOCOLIBRI_LIB_PATH
VRPN_VIEWPOINT_H = _vrpn_Analog.VRPN_VIEWPOINT_H
VRPN_VIEWPOINT_LIB_PATH = _vrpn_Analog.VRPN_VIEWPOINT_LIB_PATH
VRPN_HDAPI_PATH = _vrpn_Analog.VRPN_HDAPI_PATH
VRPN_HDAPI_UTIL_PATH = _vrpn_Analog.VRPN_HDAPI_UTIL_PATH
VRPN_GHOST_31_PATH = _vrpn_Analog.VRPN_GHOST_31_PATH
VRPN_GHOST_40_PATH = _vrpn_Analog.VRPN_GHOST_40_PATH
VRPN_NIDAQ_PATH = _vrpn_Analog.VRPN_NIDAQ_PATH
VRPN_NIDAQ_MX_PATH = _vrpn_Analog.VRPN_NIDAQ_MX_PATH
VRPN_USDIGITAL_PATH = _vrpn_Analog.VRPN_USDIGITAL_PATH
LISTEN = _vrpn_Analog.LISTEN
CONNECTED = _vrpn_Analog.CONNECTED
COOKIE_PENDING = _vrpn_Analog.COOKIE_PENDING
TRYING_TO_CONNECT = _vrpn_Analog.TRYING_TO_CONNECT
BROKEN = _vrpn_Analog.BROKEN
LOGGING = _vrpn_Analog.LOGGING
class vrpn_HANDLERPARAM:
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, vrpn_HANDLERPARAM, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, vrpn_HANDLERPARAM, name)
    __repr__ = _swig_repr
    __swig_setmethods__["type"] = _vrpn_Analog.vrpn_HANDLERPARAM_type_set
    __swig_getmethods__["type"] = _vrpn_Analog.vrpn_HANDLERPARAM_type_get
    __swig_setmethods__["sender"] = _vrpn_Analog.vrpn_HANDLERPARAM_sender_set
    __swig_getmethods__["sender"] = _vrpn_Analog.vrpn_HANDLERPARAM_sender_get
    __swig_setmethods__["msg_time"] = _vrpn_Analog.vrpn_HANDLERPARAM_msg_time_set
    __swig_getmethods__["msg_time"] = _vrpn_Analog.vrpn_HANDLERPARAM_msg_time_get
    __swig_setmethods__["payload_len"] = _vrpn_Analog.vrpn_HANDLERPARAM_payload_len_set
    __swig_getmethods__["payload_len"] = _vrpn_Analog.vrpn_HANDLERPARAM_payload_len_get
    __swig_setmethods__["buffer"] = _vrpn_Analog.vrpn_HANDLERPARAM_buffer_set
    __swig_getmethods__["buffer"] = _vrpn_Analog.vrpn_HANDLERPARAM_buffer_get
    def __init__(self): 
        this = _vrpn_Analog.new_vrpn_HANDLERPARAM()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _vrpn_Analog.delete_vrpn_HANDLERPARAM
    __del__ = lambda self : None;
vrpn_HANDLERPARAM_swigregister = _vrpn_Analog.vrpn_HANDLERPARAM_swigregister
vrpn_HANDLERPARAM_swigregister(vrpn_HANDLERPARAM)

class vrpn_LOGLIST:
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, vrpn_LOGLIST, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, vrpn_LOGLIST, name)
    __repr__ = _swig_repr
    __swig_setmethods__["data"] = _vrpn_Analog.vrpn_LOGLIST_data_set
    __swig_getmethods__["data"] = _vrpn_Analog.vrpn_LOGLIST_data_get
    __swig_setmethods__["next"] = _vrpn_Analog.vrpn_LOGLIST_next_set
    __swig_getmethods__["next"] = _vrpn_Analog.vrpn_LOGLIST_next_get
    __swig_setmethods__["prev"] = _vrpn_Analog.vrpn_LOGLIST_prev_set
    __swig_getmethods__["prev"] = _vrpn_Analog.vrpn_LOGLIST_prev_get
    def __init__(self): 
        this = _vrpn_Analog.new_vrpn_LOGLIST()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _vrpn_Analog.delete_vrpn_LOGLIST
    __del__ = lambda self : None;
vrpn_LOGLIST_swigregister = _vrpn_Analog.vrpn_LOGLIST_swigregister
vrpn_LOGLIST_swigregister(vrpn_LOGLIST)
cvar = _vrpn_Analog.cvar
vrpn_ALIGN = cvar.vrpn_ALIGN
vrpn_CONNECTION_MAX_SENDERS = cvar.vrpn_CONNECTION_MAX_SENDERS
vrpn_CONNECTION_MAX_TYPES = cvar.vrpn_CONNECTION_MAX_TYPES
vrpn_ANY_SENDER = cvar.vrpn_ANY_SENDER
vrpn_ANY_TYPE = cvar.vrpn_ANY_TYPE
vrpn_CONNECTION_TCP_BUFLEN = cvar.vrpn_CONNECTION_TCP_BUFLEN
vrpn_CONNECTION_UDP_BUFLEN = cvar.vrpn_CONNECTION_UDP_BUFLEN
vrpn_MAX_ENDPOINTS = cvar.vrpn_MAX_ENDPOINTS
vrpn_CONNECTION_SENDER_DESCRIPTION = cvar.vrpn_CONNECTION_SENDER_DESCRIPTION
vrpn_CONNECTION_TYPE_DESCRIPTION = cvar.vrpn_CONNECTION_TYPE_DESCRIPTION
vrpn_CONNECTION_UDP_DESCRIPTION = cvar.vrpn_CONNECTION_UDP_DESCRIPTION
vrpn_CONNECTION_LOG_DESCRIPTION = cvar.vrpn_CONNECTION_LOG_DESCRIPTION
vrpn_CONNECTION_DISCONNECT_MESSAGE = cvar.vrpn_CONNECTION_DISCONNECT_MESSAGE
vrpn_CONNECTION_RELIABLE = cvar.vrpn_CONNECTION_RELIABLE
vrpn_CONNECTION_FIXED_LATENCY = cvar.vrpn_CONNECTION_FIXED_LATENCY
vrpn_CONNECTION_LOW_LATENCY = cvar.vrpn_CONNECTION_LOW_LATENCY
vrpn_CONNECTION_FIXED_THROUGHPUT = cvar.vrpn_CONNECTION_FIXED_THROUGHPUT
vrpn_CONNECTION_HIGH_THROUGHPUT = cvar.vrpn_CONNECTION_HIGH_THROUGHPUT
vrpn_LOG_NONE = cvar.vrpn_LOG_NONE
vrpn_LOG_INCOMING = cvar.vrpn_LOG_INCOMING
vrpn_LOG_OUTGOING = cvar.vrpn_LOG_OUTGOING

class vrpnMsgCallbackEntry:
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, vrpnMsgCallbackEntry, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, vrpnMsgCallbackEntry, name)
    __repr__ = _swig_repr
    __swig_setmethods__["handler"] = _vrpn_Analog.vrpnMsgCallbackEntry_handler_set
    __swig_getmethods__["handler"] = _vrpn_Analog.vrpnMsgCallbackEntry_handler_get
    __swig_setmethods__["userdata"] = _vrpn_Analog.vrpnMsgCallbackEntry_userdata_set
    __swig_getmethods__["userdata"] = _vrpn_Analog.vrpnMsgCallbackEntry_userdata_get
    __swig_setmethods__["sender"] = _vrpn_Analog.vrpnMsgCallbackEntry_sender_set
    __swig_getmethods__["sender"] = _vrpn_Analog.vrpnMsgCallbackEntry_sender_get
    __swig_setmethods__["next"] = _vrpn_Analog.vrpnMsgCallbackEntry_next_set
    __swig_getmethods__["next"] = _vrpn_Analog.vrpnMsgCallbackEntry_next_get
    def __init__(self): 
        this = _vrpn_Analog.new_vrpnMsgCallbackEntry()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _vrpn_Analog.delete_vrpnMsgCallbackEntry
    __del__ = lambda self : None;
vrpnMsgCallbackEntry_swigregister = _vrpn_Analog.vrpnMsgCallbackEntry_swigregister
vrpnMsgCallbackEntry_swigregister(vrpnMsgCallbackEntry)

class vrpnLogFilterEntry:
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, vrpnLogFilterEntry, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, vrpnLogFilterEntry, name)
    __repr__ = _swig_repr
    __swig_setmethods__["filter"] = _vrpn_Analog.vrpnLogFilterEntry_filter_set
    __swig_getmethods__["filter"] = _vrpn_Analog.vrpnLogFilterEntry_filter_get
    __swig_setmethods__["userdata"] = _vrpn_Analog.vrpnLogFilterEntry_userdata_set
    __swig_getmethods__["userdata"] = _vrpn_Analog.vrpnLogFilterEntry_userdata_get
    __swig_setmethods__["next"] = _vrpn_Analog.vrpnLogFilterEntry_next_set
    __swig_getmethods__["next"] = _vrpn_Analog.vrpnLogFilterEntry_next_get
    def __init__(self): 
        this = _vrpn_Analog.new_vrpnLogFilterEntry()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _vrpn_Analog.delete_vrpnLogFilterEntry
    __del__ = lambda self : None;
vrpnLogFilterEntry_swigregister = _vrpn_Analog.vrpnLogFilterEntry_swigregister
vrpnLogFilterEntry_swigregister(vrpnLogFilterEntry)

class vrpn_Endpoint:
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, vrpn_Endpoint, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, vrpn_Endpoint, name)
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _vrpn_Analog.delete_vrpn_Endpoint
    __del__ = lambda self : None;
    def local_type_id(self, *args): return _vrpn_Analog.vrpn_Endpoint_local_type_id(self, *args)
    def local_sender_id(self, *args): return _vrpn_Analog.vrpn_Endpoint_local_sender_id(self, *args)
    def doing_okay(self): return _vrpn_Analog.vrpn_Endpoint_doing_okay(self)
    def init(self): return _vrpn_Analog.vrpn_Endpoint_init(self)
    def mainloop(self, *args): return _vrpn_Analog.vrpn_Endpoint_mainloop(self, *args)
    def clear_other_senders_and_types(self): return _vrpn_Analog.vrpn_Endpoint_clear_other_senders_and_types(self)
    def newLocalSender(self, *args): return _vrpn_Analog.vrpn_Endpoint_newLocalSender(self, *args)
    def newLocalType(self, *args): return _vrpn_Analog.vrpn_Endpoint_newLocalType(self, *args)
    def newRemoteType(self, *args): return _vrpn_Analog.vrpn_Endpoint_newRemoteType(self, *args)
    def newRemoteSender(self, *args): return _vrpn_Analog.vrpn_Endpoint_newRemoteSender(self, *args)
    def pack_message(self, *args): return _vrpn_Analog.vrpn_Endpoint_pack_message(self, *args)
    def send_pending_reports(self): return _vrpn_Analog.vrpn_Endpoint_send_pending_reports(self)
    def pack_log_description(self): return _vrpn_Analog.vrpn_Endpoint_pack_log_description(self)
    def setup_new_connection(self): return _vrpn_Analog.vrpn_Endpoint_setup_new_connection(self)
    def poll_for_cookie(self, timeout = None): return _vrpn_Analog.vrpn_Endpoint_poll_for_cookie(self, timeout)
    def finish_new_connection_setup(self): return _vrpn_Analog.vrpn_Endpoint_finish_new_connection_setup(self)
    def drop_connection(self): return _vrpn_Analog.vrpn_Endpoint_drop_connection(self)
    def clearBuffers(self): return _vrpn_Analog.vrpn_Endpoint_clearBuffers(self)
    def pack_sender_description(self, *args): return _vrpn_Analog.vrpn_Endpoint_pack_sender_description(self, *args)
    def pack_type_description(self, *args): return _vrpn_Analog.vrpn_Endpoint_pack_type_description(self, *args)
    __swig_setmethods__["status"] = _vrpn_Analog.vrpn_Endpoint_status_set
    __swig_getmethods__["status"] = _vrpn_Analog.vrpn_Endpoint_status_get
    __swig_setmethods__["d_remoteLogMode"] = _vrpn_Analog.vrpn_Endpoint_d_remoteLogMode_set
    __swig_getmethods__["d_remoteLogMode"] = _vrpn_Analog.vrpn_Endpoint_d_remoteLogMode_get
    __swig_setmethods__["d_remoteInLogName"] = _vrpn_Analog.vrpn_Endpoint_d_remoteInLogName_set
    __swig_getmethods__["d_remoteInLogName"] = _vrpn_Analog.vrpn_Endpoint_d_remoteInLogName_get
    __swig_setmethods__["d_remoteOutLogName"] = _vrpn_Analog.vrpn_Endpoint_d_remoteOutLogName_set
    __swig_getmethods__["d_remoteOutLogName"] = _vrpn_Analog.vrpn_Endpoint_d_remoteOutLogName_get
    __swig_setmethods__["rhostname"] = _vrpn_Analog.vrpn_Endpoint_rhostname_set
    __swig_getmethods__["rhostname"] = _vrpn_Analog.vrpn_Endpoint_rhostname_get
    __swig_setmethods__["d_inLog"] = _vrpn_Analog.vrpn_Endpoint_d_inLog_set
    __swig_getmethods__["d_inLog"] = _vrpn_Analog.vrpn_Endpoint_d_inLog_get
    __swig_setmethods__["d_outLog"] = _vrpn_Analog.vrpn_Endpoint_d_outLog_set
    __swig_getmethods__["d_outLog"] = _vrpn_Analog.vrpn_Endpoint_d_outLog_get
    def setLogNames(self, *args): return _vrpn_Analog.vrpn_Endpoint_setLogNames(self, *args)
    def openLogs(self): return _vrpn_Analog.vrpn_Endpoint_openLogs(self)
    __swig_getmethods__["handle_sender_message"] = lambda x: _vrpn_Analog.vrpn_Endpoint_handle_sender_message
    __swig_getmethods__["handle_type_message"] = lambda x: _vrpn_Analog.vrpn_Endpoint_handle_type_message
    def setConnection(self, *args): return _vrpn_Analog.vrpn_Endpoint_setConnection(self, *args)
    def getConnection(self): return _vrpn_Analog.vrpn_Endpoint_getConnection(self)
vrpn_Endpoint_swigregister = _vrpn_Analog.vrpn_Endpoint_swigregister
vrpn_Endpoint_swigregister(vrpn_Endpoint)

def vrpn_Endpoint_handle_sender_message(*args):
  return _vrpn_Analog.vrpn_Endpoint_handle_sender_message(*args)
vrpn_Endpoint_handle_sender_message = _vrpn_Analog.vrpn_Endpoint_handle_sender_message

def vrpn_Endpoint_handle_type_message(*args):
  return _vrpn_Analog.vrpn_Endpoint_handle_type_message(*args)
vrpn_Endpoint_handle_type_message = _vrpn_Analog.vrpn_Endpoint_handle_type_message

class vrpn_Endpoint_IP(vrpn_Endpoint):
    __swig_setmethods__ = {}
    for _s in [vrpn_Endpoint]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, vrpn_Endpoint_IP, name, value)
    __swig_getmethods__ = {}
    for _s in [vrpn_Endpoint]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, vrpn_Endpoint_IP, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _vrpn_Analog.new_vrpn_Endpoint_IP(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _vrpn_Analog.delete_vrpn_Endpoint_IP
    __del__ = lambda self : None;
    def doing_okay(self): return _vrpn_Analog.vrpn_Endpoint_IP_doing_okay(self)
    def outbound_udp_open(self): return _vrpn_Analog.vrpn_Endpoint_IP_outbound_udp_open(self)
    def tcp_outbuf_size(self): return _vrpn_Analog.vrpn_Endpoint_IP_tcp_outbuf_size(self)
    def udp_outbuf_size(self): return _vrpn_Analog.vrpn_Endpoint_IP_udp_outbuf_size(self)
    def init(self): return _vrpn_Analog.vrpn_Endpoint_IP_init(self)
    def mainloop(self, *args): return _vrpn_Analog.vrpn_Endpoint_IP_mainloop(self, *args)
    def pack_message(self, *args): return _vrpn_Analog.vrpn_Endpoint_IP_pack_message(self, *args)
    def send_pending_reports(self): return _vrpn_Analog.vrpn_Endpoint_IP_send_pending_reports(self)
    def pack_udp_description(self, *args): return _vrpn_Analog.vrpn_Endpoint_IP_pack_udp_description(self, *args)
    def handle_tcp_messages(self, *args): return _vrpn_Analog.vrpn_Endpoint_IP_handle_tcp_messages(self, *args)
    def handle_udp_messages(self, *args): return _vrpn_Analog.vrpn_Endpoint_IP_handle_udp_messages(self, *args)
    def connect_tcp_to(self, *args): return _vrpn_Analog.vrpn_Endpoint_IP_connect_tcp_to(self, *args)
    def connect_udp_to(self, *args): return _vrpn_Analog.vrpn_Endpoint_IP_connect_udp_to(self, *args)
    def set_tcp_outbuf_size(self, *args): return _vrpn_Analog.vrpn_Endpoint_IP_set_tcp_outbuf_size(self, *args)
    def setup_new_connection(self): return _vrpn_Analog.vrpn_Endpoint_IP_setup_new_connection(self)
    def poll_for_cookie(self, timeout = None): return _vrpn_Analog.vrpn_Endpoint_IP_poll_for_cookie(self, timeout)
    def finish_new_connection_setup(self): return _vrpn_Analog.vrpn_Endpoint_IP_finish_new_connection_setup(self)
    def drop_connection(self): return _vrpn_Analog.vrpn_Endpoint_IP_drop_connection(self)
    def clearBuffers(self): return _vrpn_Analog.vrpn_Endpoint_IP_clearBuffers(self)
    def setNICaddress(self, *args): return _vrpn_Analog.vrpn_Endpoint_IP_setNICaddress(self, *args)
    __swig_setmethods__["d_tcpSocket"] = _vrpn_Analog.vrpn_Endpoint_IP_d_tcpSocket_set
    __swig_getmethods__["d_tcpSocket"] = _vrpn_Analog.vrpn_Endpoint_IP_d_tcpSocket_get
    __swig_setmethods__["d_tcpListenSocket"] = _vrpn_Analog.vrpn_Endpoint_IP_d_tcpListenSocket_set
    __swig_getmethods__["d_tcpListenSocket"] = _vrpn_Analog.vrpn_Endpoint_IP_d_tcpListenSocket_get
    __swig_setmethods__["d_tcpListenPort"] = _vrpn_Analog.vrpn_Endpoint_IP_d_tcpListenPort_set
    __swig_getmethods__["d_tcpListenPort"] = _vrpn_Analog.vrpn_Endpoint_IP_d_tcpListenPort_get
    __swig_setmethods__["d_remote_machine_name"] = _vrpn_Analog.vrpn_Endpoint_IP_d_remote_machine_name_set
    __swig_getmethods__["d_remote_machine_name"] = _vrpn_Analog.vrpn_Endpoint_IP_d_remote_machine_name_get
    __swig_setmethods__["d_remote_port_number"] = _vrpn_Analog.vrpn_Endpoint_IP_d_remote_port_number_set
    __swig_getmethods__["d_remote_port_number"] = _vrpn_Analog.vrpn_Endpoint_IP_d_remote_port_number_get
    __swig_setmethods__["d_last_connect_attempt"] = _vrpn_Analog.vrpn_Endpoint_IP_d_last_connect_attempt_set
    __swig_getmethods__["d_last_connect_attempt"] = _vrpn_Analog.vrpn_Endpoint_IP_d_last_connect_attempt_get
    __swig_setmethods__["d_tcp_only"] = _vrpn_Analog.vrpn_Endpoint_IP_d_tcp_only_set
    __swig_getmethods__["d_tcp_only"] = _vrpn_Analog.vrpn_Endpoint_IP_d_tcp_only_get
vrpn_Endpoint_IP_swigregister = _vrpn_Analog.vrpn_Endpoint_IP_swigregister
vrpn_Endpoint_IP_swigregister(vrpn_Endpoint_IP)

class vrpn_Connection:
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, vrpn_Connection, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, vrpn_Connection, name)
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _vrpn_Analog.delete_vrpn_Connection
    __del__ = lambda self : None;
    def doing_okay(self): return _vrpn_Analog.vrpn_Connection_doing_okay(self)
    def connected(self): return _vrpn_Analog.vrpn_Connection_connected(self)
    def get_log_names(self, *args): return _vrpn_Analog.vrpn_Connection_get_log_names(self, *args)
    def mainloop(self, timeout = None): return _vrpn_Analog.vrpn_Connection_mainloop(self, timeout)
    def register_sender(self, *args): return _vrpn_Analog.vrpn_Connection_register_sender(self, *args)
    def register_message_type(self, *args): return _vrpn_Analog.vrpn_Connection_register_message_type(self, *args)
    def register_handler(self, *args): return _vrpn_Analog.vrpn_Connection_register_handler(self, *args)
    def unregister_handler(self, *args): return _vrpn_Analog.vrpn_Connection_unregister_handler(self, *args)
    def pack_message(self, *args): return _vrpn_Analog.vrpn_Connection_pack_message(self, *args)
    def send_pending_reports(self): return _vrpn_Analog.vrpn_Connection_send_pending_reports(self)
    def time_since_connection_open(self, *args): return _vrpn_Analog.vrpn_Connection_time_since_connection_open(self, *args)
    def get_time(self): return _vrpn_Analog.vrpn_Connection_get_time(self)
    def sender_name(self, *args): return _vrpn_Analog.vrpn_Connection_sender_name(self, *args)
    def message_type_name(self, *args): return _vrpn_Analog.vrpn_Connection_message_type_name(self, *args)
    def register_log_filter(self, *args): return _vrpn_Analog.vrpn_Connection_register_log_filter(self, *args)
    def save_log_so_far(self): return _vrpn_Analog.vrpn_Connection_save_log_so_far(self)
    def get_File_Connection(self): return _vrpn_Analog.vrpn_Connection_get_File_Connection(self)
    def Jane_stop_this_crazy_thing(self, *args): return _vrpn_Analog.vrpn_Connection_Jane_stop_this_crazy_thing(self, *args)
    def get_Jane_value(self): return _vrpn_Analog.vrpn_Connection_get_Jane_value(self)
    def addReference(self): return _vrpn_Analog.vrpn_Connection_addReference(self)
    def removeReference(self): return _vrpn_Analog.vrpn_Connection_removeReference(self)
    def setAutoDeleteStatus(self, *args): return _vrpn_Analog.vrpn_Connection_setAutoDeleteStatus(self, *args)
    __swig_setmethods__["d_dispatcher"] = _vrpn_Analog.vrpn_Connection_d_dispatcher_set
    __swig_getmethods__["d_dispatcher"] = _vrpn_Analog.vrpn_Connection_d_dispatcher_get
vrpn_Connection_swigregister = _vrpn_Analog.vrpn_Connection_swigregister
vrpn_Connection_swigregister(vrpn_Connection)

class vrpn_Connection_IP(vrpn_Connection):
    __swig_setmethods__ = {}
    for _s in [vrpn_Connection]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, vrpn_Connection_IP, name, value)
    __swig_getmethods__ = {}
    for _s in [vrpn_Connection]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, vrpn_Connection_IP, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _vrpn_Analog.new_vrpn_Connection_IP(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _vrpn_Analog.delete_vrpn_Connection_IP
    __del__ = lambda self : None;
    def connect_to_client(self, *args): return _vrpn_Analog.vrpn_Connection_IP_connect_to_client(self, *args)
    def mainloop(self, timeout = None): return _vrpn_Analog.vrpn_Connection_IP_mainloop(self, timeout)
vrpn_Connection_IP_swigregister = _vrpn_Analog.vrpn_Connection_IP_swigregister
vrpn_Connection_IP_swigregister(vrpn_Connection_IP)


def vrpn_copy_service_name(*args):
  return _vrpn_Analog.vrpn_copy_service_name(*args)
vrpn_copy_service_name = _vrpn_Analog.vrpn_copy_service_name

def vrpn_copy_service_location(*args):
  return _vrpn_Analog.vrpn_copy_service_location(*args)
vrpn_copy_service_location = _vrpn_Analog.vrpn_copy_service_location

def vrpn_copy_file_name(*args):
  return _vrpn_Analog.vrpn_copy_file_name(*args)
vrpn_copy_file_name = _vrpn_Analog.vrpn_copy_file_name

def vrpn_copy_machine_name(*args):
  return _vrpn_Analog.vrpn_copy_machine_name(*args)
vrpn_copy_machine_name = _vrpn_Analog.vrpn_copy_machine_name

def vrpn_get_port_number(*args):
  return _vrpn_Analog.vrpn_get_port_number(*args)
vrpn_get_port_number = _vrpn_Analog.vrpn_get_port_number

def vrpn_copy_rsh_program(*args):
  return _vrpn_Analog.vrpn_copy_rsh_program(*args)
vrpn_copy_rsh_program = _vrpn_Analog.vrpn_copy_rsh_program

def vrpn_copy_rsh_arguments(*args):
  return _vrpn_Analog.vrpn_copy_rsh_arguments(*args)
vrpn_copy_rsh_arguments = _vrpn_Analog.vrpn_copy_rsh_arguments

def vrpn_set_service_name(*args):
  return _vrpn_Analog.vrpn_set_service_name(*args)
vrpn_set_service_name = _vrpn_Analog.vrpn_set_service_name

def check_vrpn_cookie(*args):
  return _vrpn_Analog.check_vrpn_cookie(*args)
check_vrpn_cookie = _vrpn_Analog.check_vrpn_cookie

def check_vrpn_file_cookie(*args):
  return _vrpn_Analog.check_vrpn_file_cookie(*args)
check_vrpn_file_cookie = _vrpn_Analog.check_vrpn_file_cookie

def vrpn_cookie_size():
  return _vrpn_Analog.vrpn_cookie_size()
vrpn_cookie_size = _vrpn_Analog.vrpn_cookie_size

def write_vrpn_cookie(*args):
  return _vrpn_Analog.write_vrpn_cookie(*args)
write_vrpn_cookie = _vrpn_Analog.write_vrpn_cookie

def vrpn_noint_block_write(*args):
  return _vrpn_Analog.vrpn_noint_block_write(*args)
vrpn_noint_block_write = _vrpn_Analog.vrpn_noint_block_write

def vrpn_noint_block_read(*args):
  return _vrpn_Analog.vrpn_noint_block_read(*args)
vrpn_noint_block_read = _vrpn_Analog.vrpn_noint_block_read

def vrpn_noint_select(*args):
  return _vrpn_Analog.vrpn_noint_select(*args)
vrpn_noint_select = _vrpn_Analog.vrpn_noint_select
class vrpn_ConnectionManager:
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, vrpn_ConnectionManager, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, vrpn_ConnectionManager, name)
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    __swig_destroy__ = _vrpn_Analog.delete_vrpn_ConnectionManager
    __del__ = lambda self : None;
    __swig_getmethods__["instance"] = lambda x: _vrpn_Analog.vrpn_ConnectionManager_instance
    def addConnection(self, *args): return _vrpn_Analog.vrpn_ConnectionManager_addConnection(self, *args)
    def deleteConnection(self, *args): return _vrpn_Analog.vrpn_ConnectionManager_deleteConnection(self, *args)
    def getByName(self, *args): return _vrpn_Analog.vrpn_ConnectionManager_getByName(self, *args)
vrpn_ConnectionManager_swigregister = _vrpn_Analog.vrpn_ConnectionManager_swigregister
vrpn_ConnectionManager_swigregister(vrpn_ConnectionManager)

def vrpn_get_connection_by_name(*args):
  return _vrpn_Analog.vrpn_get_connection_by_name(*args)
vrpn_get_connection_by_name = _vrpn_Analog.vrpn_get_connection_by_name

def vrpn_create_server_connection(*args):
  return _vrpn_Analog.vrpn_create_server_connection(*args)
vrpn_create_server_connection = _vrpn_Analog.vrpn_create_server_connection

def vrpn_ConnectionManager_instance():
  return _vrpn_Analog.vrpn_ConnectionManager_instance()
vrpn_ConnectionManager_instance = _vrpn_Analog.vrpn_ConnectionManager_instance

vrpn_TEXT_NORMAL = _vrpn_Analog.vrpn_TEXT_NORMAL
vrpn_TEXT_WARNING = _vrpn_Analog.vrpn_TEXT_WARNING
vrpn_TEXT_ERROR = _vrpn_Analog.vrpn_TEXT_ERROR
class vrpn_TextPrinter:
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, vrpn_TextPrinter, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, vrpn_TextPrinter, name)
    __repr__ = _swig_repr
    def __init__(self): 
        this = _vrpn_Analog.new_vrpn_TextPrinter()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _vrpn_Analog.delete_vrpn_TextPrinter
    __del__ = lambda self : None;
    def add_object(self, *args): return _vrpn_Analog.vrpn_TextPrinter_add_object(self, *args)
    def remove_object(self, *args): return _vrpn_Analog.vrpn_TextPrinter_remove_object(self, *args)
    def set_min_level_to_print(self, *args): return _vrpn_Analog.vrpn_TextPrinter_set_min_level_to_print(self, *args)
    def set_ostream_to_use(self, *args): return _vrpn_Analog.vrpn_TextPrinter_set_ostream_to_use(self, *args)
vrpn_TextPrinter_swigregister = _vrpn_Analog.vrpn_TextPrinter_swigregister
vrpn_TextPrinter_swigregister(vrpn_TextPrinter)
vrpn_MAX_BCADRS = cvar.vrpn_MAX_BCADRS
vrpn_MAX_TEXT_LEN = cvar.vrpn_MAX_TEXT_LEN

class vrpn_BaseClassUnique:
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, vrpn_BaseClassUnique, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, vrpn_BaseClassUnique, name)
    __repr__ = _swig_repr
    def __init__(self): 
        this = _vrpn_Analog.new_vrpn_BaseClassUnique()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _vrpn_Analog.delete_vrpn_BaseClassUnique
    __del__ = lambda self : None;
    __swig_setmethods__["shutup"] = _vrpn_Analog.vrpn_BaseClassUnique_shutup_set
    __swig_getmethods__["shutup"] = _vrpn_Analog.vrpn_BaseClassUnique_shutup_get
vrpn_BaseClassUnique_swigregister = _vrpn_Analog.vrpn_BaseClassUnique_swigregister
vrpn_BaseClassUnique_swigregister(vrpn_BaseClassUnique)

class vrpn_BaseClass(vrpn_BaseClassUnique):
    __swig_setmethods__ = {}
    for _s in [vrpn_BaseClassUnique]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, vrpn_BaseClass, name, value)
    __swig_getmethods__ = {}
    for _s in [vrpn_BaseClassUnique]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, vrpn_BaseClass, name)
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _vrpn_Analog.delete_vrpn_BaseClass
    __del__ = lambda self : None;
    def mainloop(self): return _vrpn_Analog.vrpn_BaseClass_mainloop(self)
    def connectionPtr(self): return _vrpn_Analog.vrpn_BaseClass_connectionPtr(self)
vrpn_BaseClass_swigregister = _vrpn_Analog.vrpn_BaseClass_swigregister
vrpn_BaseClass_swigregister(vrpn_BaseClass)

vrpn_CHANNEL_MAX = _vrpn_Analog.vrpn_CHANNEL_MAX
class vrpn_Analog(vrpn_BaseClass):
    __swig_setmethods__ = {}
    for _s in [vrpn_BaseClass]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, vrpn_Analog, name, value)
    __swig_getmethods__ = {}
    for _s in [vrpn_BaseClass]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, vrpn_Analog, name)
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    def _print(self): return _vrpn_Analog.vrpn_Analog__print(self)
    def getNumChannels(self): return _vrpn_Analog.vrpn_Analog_getNumChannels(self)
    __swig_destroy__ = _vrpn_Analog.delete_vrpn_Analog
    __del__ = lambda self : None;
vrpn_Analog_swigregister = _vrpn_Analog.vrpn_Analog_swigregister
vrpn_Analog_swigregister(vrpn_Analog)
vrpn_ANALOG_SYNCING = cvar.vrpn_ANALOG_SYNCING
vrpn_ANALOG_REPORT_READY = cvar.vrpn_ANALOG_REPORT_READY
vrpn_ANALOG_PARTIAL = cvar.vrpn_ANALOG_PARTIAL
vrpn_ANALOG_RESETTING = cvar.vrpn_ANALOG_RESETTING
vrpn_ANALOG_FAIL = cvar.vrpn_ANALOG_FAIL
vrpn_ANALOG_NOW = cvar.vrpn_ANALOG_NOW

class vrpn_Serial_Analog(vrpn_Analog):
    __swig_setmethods__ = {}
    for _s in [vrpn_Analog]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, vrpn_Serial_Analog, name, value)
    __swig_getmethods__ = {}
    for _s in [vrpn_Analog]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, vrpn_Serial_Analog, name)
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _vrpn_Analog.delete_vrpn_Serial_Analog
    __del__ = lambda self : None;
vrpn_Serial_Analog_swigregister = _vrpn_Analog.vrpn_Serial_Analog_swigregister
vrpn_Serial_Analog_swigregister(vrpn_Serial_Analog)

class vrpn_Analog_Server(vrpn_Analog):
    __swig_setmethods__ = {}
    for _s in [vrpn_Analog]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, vrpn_Analog_Server, name, value)
    __swig_getmethods__ = {}
    for _s in [vrpn_Analog]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, vrpn_Analog_Server, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _vrpn_Analog.new_vrpn_Analog_Server(*args)
        try: self.this.append(this)
        except: self.this = this
    def report_changes(self, *args): return _vrpn_Analog.vrpn_Analog_Server_report_changes(self, *args)
    def report(self, *args): return _vrpn_Analog.vrpn_Analog_Server_report(self, *args)
    def mainloop(self): return _vrpn_Analog.vrpn_Analog_Server_mainloop(self)
    def channels(self): return _vrpn_Analog.vrpn_Analog_Server_channels(self)
    def setNumChannels(self, *args): return _vrpn_Analog.vrpn_Analog_Server_setNumChannels(self, *args)
    __swig_destroy__ = _vrpn_Analog.delete_vrpn_Analog_Server
    __del__ = lambda self : None;
vrpn_Analog_Server_swigregister = _vrpn_Analog.vrpn_Analog_Server_swigregister
vrpn_Analog_Server_swigregister(vrpn_Analog_Server)

class vrpn_Clipping_Analog_Server(vrpn_Analog_Server):
    __swig_setmethods__ = {}
    for _s in [vrpn_Analog_Server]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, vrpn_Clipping_Analog_Server, name, value)
    __swig_getmethods__ = {}
    for _s in [vrpn_Analog_Server]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, vrpn_Clipping_Analog_Server, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _vrpn_Analog.new_vrpn_Clipping_Analog_Server(*args)
        try: self.this.append(this)
        except: self.this = this
    def setClipValues(self, *args): return _vrpn_Analog.vrpn_Clipping_Analog_Server_setClipValues(self, *args)
    def setChannelValue(self, *args): return _vrpn_Analog.vrpn_Clipping_Analog_Server_setChannelValue(self, *args)
    __swig_destroy__ = _vrpn_Analog.delete_vrpn_Clipping_Analog_Server
    __del__ = lambda self : None;
vrpn_Clipping_Analog_Server_swigregister = _vrpn_Analog.vrpn_Clipping_Analog_Server_swigregister
vrpn_Clipping_Analog_Server_swigregister(vrpn_Clipping_Analog_Server)

class vrpn_ANALOGCB:
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, vrpn_ANALOGCB, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, vrpn_ANALOGCB, name)
    __repr__ = _swig_repr
    __swig_setmethods__["msg_time"] = _vrpn_Analog.vrpn_ANALOGCB_msg_time_set
    __swig_getmethods__["msg_time"] = _vrpn_Analog.vrpn_ANALOGCB_msg_time_get
    __swig_setmethods__["num_channel"] = _vrpn_Analog.vrpn_ANALOGCB_num_channel_set
    __swig_getmethods__["num_channel"] = _vrpn_Analog.vrpn_ANALOGCB_num_channel_get
    __swig_setmethods__["channel"] = _vrpn_Analog.vrpn_ANALOGCB_channel_set
    __swig_getmethods__["channel"] = _vrpn_Analog.vrpn_ANALOGCB_channel_get
    def __init__(self): 
        this = _vrpn_Analog.new_vrpn_ANALOGCB()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _vrpn_Analog.delete_vrpn_ANALOGCB
    __del__ = lambda self : None;
vrpn_ANALOGCB_swigregister = _vrpn_Analog.vrpn_ANALOGCB_swigregister
vrpn_ANALOGCB_swigregister(vrpn_ANALOGCB)

class vrpn_Analog_Remote(vrpn_Analog):
    __swig_setmethods__ = {}
    for _s in [vrpn_Analog]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, vrpn_Analog_Remote, name, value)
    __swig_getmethods__ = {}
    for _s in [vrpn_Analog]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, vrpn_Analog_Remote, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _vrpn_Analog.new_vrpn_Analog_Remote(*args)
        try: self.this.append(this)
        except: self.this = this
    def mainloop(self): return _vrpn_Analog.vrpn_Analog_Remote_mainloop(self)
    def register_change_handler(self, *args): return _vrpn_Analog.vrpn_Analog_Remote_register_change_handler(self, *args)
    def unregister_change_handler(self, *args): return _vrpn_Analog.vrpn_Analog_Remote_unregister_change_handler(self, *args)
    __swig_destroy__ = _vrpn_Analog.delete_vrpn_Analog_Remote
    __del__ = lambda self : None;
vrpn_Analog_Remote_swigregister = _vrpn_Analog.vrpn_Analog_Remote_swigregister
vrpn_Analog_Remote_swigregister(vrpn_Analog_Remote)


def register_analog_change_handler(*args):
  return _vrpn_Analog.register_analog_change_handler(*args)
register_analog_change_handler = _vrpn_Analog.register_analog_change_handler

def get_analog_change_handler():
  return _vrpn_Analog.get_analog_change_handler()
get_analog_change_handler = _vrpn_Analog.get_analog_change_handler


